# Generated by Django 5.2.17 on 2026-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='renewal_applied',
            field=models.BooleanField(default=False),
        ),
    ]
