# Generated by Django 5.2.17 on 2026-09-11 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_clear_company_data'),
        ('road_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=4)),
                ('label', models.CharField(max_length=100)),
                ('reconciled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.virtualcompany')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('digest', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversal_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualaccount')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='road_sync.virtualaccount')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualtransaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'account'), name='sync_unique_transaction_account')],
            },
        ),
    ]
