# Generated by Django 5.2.17 on 2026-09-11 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_sync', '0002_virtualaccount_virtualtransaction_virtualinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfileBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField()),
                ('game', models.CharField(max_length=4)),
                ('profile_key', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProbe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('challenge', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.gameprofilebinding')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameprofilebinding',
            constraint=models.UniqueConstraint(fields=('user', 'installation_id', 'game'), name='sync_unique_profile_binding'),
        ),
    ]
