# Generated by Django 5.2.17 on 2026-09-11 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_sync', '0003_gameprofilebinding_agentprobe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualinvoice',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='VirtualLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('term_days', models.PositiveSmallIntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=10, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualaccount')),
                ('disbursement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='virtualinvoice',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualloan'),
        ),
    ]
