# Generated by Django 5.2.17 on 2026-09-11 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_sync', '0004_virtualinvoice_principal_virtualloan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualinvoice',
            name='amortized_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='virtualinvoice',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_invoices', to='road_sync.virtualtransaction'),
        ),
        migrations.AddField(
            model_name='virtualinvoice',
            name='waived_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='VirtualAmortization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualloan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualtransaction')),
            ],
        ),
    ]
