# Generated by Django 5.2.17 on 2026-09-11 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_sync', '0005_virtualinvoice_amortized_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualloan',
            name='kind',
            field=models.CharField(default='loan', max_length=12),
        ),
        migrations.CreateModel(
            name='VirtualAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=10)),
                ('odometer_km', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualaccount')),
                ('loan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='road_sync.virtualloan')),
                ('purchase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_purchase', to='road_sync.virtualtransaction')),
            ],
        ),
    ]
