# Generated by Django 5.2.17 on 2026-09-08 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('own_truck', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms', models.JSONField()),
                ('signed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('reputation', models.PositiveIntegerField(default=100)),
                ('license_points', models.PositiveIntegerField(default=40)),
                ('candidacy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.candidacy')),
            ],
        ),
        migrations.CreateModel(
            name='FreightEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.employeecontract')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineFreight',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=25)),
                ('result', models.JSONField(default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.employeecontract')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('game', models.CharField(max_length=4)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('rules', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.virtualcompany'),
        ),
        migrations.CreateModel(
            name='CompanyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('reference', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.virtualcompany')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('vacancy', 'player'), name='unique_player_application'),
        ),
    ]
