# Generated by Django 5.2.17 on 2026-09-08 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_directjoboffer_playerrecruitmentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=4)),
                ('cargo', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('completed_at', models.DateTimeField()),
                ('digest', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'event_id'), name='unique_autonomous_delivery')],
            },
        ),
    ]
