# Generated by Django 5.2.17 on 2026-09-08 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_autonomousdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDesktopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=64)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.virtualcompany')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'local_id'), name='unique_desktop_company')],
            },
        ),
        migrations.CreateModel(
            name='VacancyDesktopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.virtualcompany')),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.vacancy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'local_id'), name='unique_desktop_vacancy')],
            },
        ),
    ]
