# Generated by Django 5.2.17 on 2026-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companydesktoplink_vacancydesktoplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='game_profiles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='onlinefreight',
            name='game',
            field=models.CharField(default='', max_length=4),
        ),
    ]
