# Generated by Django 5.2.17 on 2026-09-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_per_game_contract_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomousdelivery',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
