# Generated by Django 5.2.17 on 2026-09-10 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_archive_freight_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do mapa')),
                ('game', models.CharField(choices=[('ETS2', 'Euro Truck Simulator 2'), ('ATS', 'American Truck Simulator')], max_length=4, verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Mapa de missão',
                'verbose_name_plural': 'Mapas de missões',
                'ordering': ['game', 'name'],
                'constraints': [models.UniqueConstraint(fields=('game', 'name'), name='unique_mission_game_map')],
            },
        ),
        migrations.CreateModel(
            name='OfficialMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Nome da missão')),
                ('description', models.TextField(verbose_name='Descrição e instruções')),
                ('game', models.CharField(choices=[('ETS2', 'Euro Truck Simulator 2'), ('ATS', 'American Truck Simulator')], max_length=4, verbose_name='Jogo')),
                ('starts_at', models.DateTimeField(verbose_name='Início (horário real)')),
                ('ends_at', models.DateTimeField(verbose_name='Prazo final (horário real)')),
                ('deliveries', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Entregas necessárias')),
                ('distance_km', models.DecimalField(decimal_places=3, default=0, help_text='Meta adicional. No ATS, 1 milha equivale a 1,609344 km. Zero: sem meta de distância.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância acumulada em km')),
                ('weight_tons', models.DecimalField(decimal_places=3, default=0, help_text='Zero: sem meta de peso.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Toneladas acumuladas')),
                ('max_damage_percent', models.DecimalField(decimal_places=2, default=5, help_text='Entregas acima do limite não contam para a missão.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Dano máximo na carga (%)')),
                ('reward_money', models.DecimalField(decimal_places=2, default=0, help_text='Valor destinado à empresa, não é dinheiro real.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recompensa em dinheiro virtual')),
                ('reward_reputation', models.PositiveIntegerField(default=0, verbose_name='Recompensa em reputação')),
                ('published', models.BooleanField(default=False, help_text='Desmarque para manter como rascunho ou retirar do catálogo.', verbose_name='Publicar missão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.missionmap', verbose_name='Mapa')),
            ],
            options={
                'verbose_name': 'Missão oficial para empresas',
                'verbose_name_plural': 'Missões oficiais para empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
