# Generated by Django 5.2.17 on 2026-09-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lifetime_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento da liberação'),
        ),
        migrations.AddField(
            model_name='user',
            name='manual_plan',
            field=models.CharField(blank=True, choices=[('', 'Sem liberação'), ('player', 'Player'), ('company', 'Empresa Virtual')], default='', max_length=12, verbose_name='Plano liberado pelo administrador'),
        ),
    ]
