# Generated by Django 5.2.17 on 2026-08-29 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('stable', 'Estável'), ('beta', 'Beta')], default='stable', max_length=12)),
                ('file', models.FileField(upload_to='installers/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('release_notes', models.TextField(blank=True)),
                ('min_plan_codes', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'unique_together': {('version', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='downloads.appversion')),
            ],
        ),
    ]
