# Generated by Django 5.2.17 on 2026-09-11 01:09

from django.db import migrations, models


def classify_uploads(apps, schema_editor):
    Version = apps.get_model("downloads", "AppVersion")
    for version in Version.objects.using(schema_editor.connection.alias).all():
        filename = str(version.file).rsplit("/", 1)[-1].lower()
        if "empresa" in filename or "company" in filename:
            version.application = "company"
        elif "player" in filename:
            version.application = "player"
        if version.min_plan_codes:
            codes = ["empresa-virtual-mensal"] if version.application == "company" else ["player-mensal", "empresa-virtual-mensal"]
            version.min_plan_codes = list(dict.fromkeys([*version.min_plan_codes, *codes]))
        version.save(update_fields=["application", "min_plan_codes"])

class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appversion',
            name='application',
            field=models.CharField(choices=[('offline', 'RoadLedger original (offline)'), ('player', 'RoadLedger Player (online)'), ('company', 'RoadLedger Empresa Virtual')], default='offline', max_length=12, verbose_name='Aplicativo'),
        ),
        migrations.RunPython(classify_uploads, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('application', 'version', 'channel')},
        ),
    ]
