# Generated by Django 5.2.17 on 2026-09-11 01:09

from django.db import migrations, models


def preserve_existing_access(apps, schema_editor):
    # Existing subscribers previously had access to every application.
    apps.get_model("subscriptions", "Plan").objects.using(schema_editor.connection.alias).all().update(product="company")

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_provider_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.CharField(choices=[('player', 'Player — offline e online'), ('company', 'Empresa Virtual — os três aplicativos')], default='player', max_length=12, verbose_name='Aplicativos incluídos'),
        ),
        migrations.RunPython(preserve_existing_access, migrations.RunPython.noop),
    ]
