# Generated by Django 5.2.17 on 2026-09-11 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_player_company_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_coverage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_end', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Concluindo troca'), ('applied', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=12)),
                ('checkout_url', models.URLField(blank=True, max_length=600)),
                ('payment_id', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('previous_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_from', to='subscriptions.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_changes', to='subscriptions.subscription')),
                ('target_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_to', to='subscriptions.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid'])), fields=('subscription',), name='one_open_plan_change')],
            },
        ),
    ]
