# Generated by Django 5.2.17 on 2026-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_billing_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchange',
            name='operation',
            field=models.CharField(choices=[('change', 'Troca de plano'), ('renewal', 'Renovação PIX')], default='change', max_length=12),
        ),
    ]
